services:
  app:
    image: ghcr.io/liena-grytsyna/intern-chat:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - CHAT_DB_PATH=storage/chat.db
    volumes:
      - chat-data:/usr/src/app/storage

volumes:
  chat-data:
